const Actions = {
    COUNTER_INCREMENT: 'INCREMENT',
    COUNTER_DECREMENT: 'DECREMENT',
    FETCH_POSTS: 'FETCH_POSTS',
    GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
    GOOGLE_LOGIN_FAILED: 'GOOGLE_LOGIN_FAILED',
    GOOGLE_LOGIN_ERROR: 'GOOGLE_LOGIN_ERROR'
}

export default Actions